meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path(
        "create/",
        MealPlanCreateView.as_view(),
        name="meal_plans_create",
    ),
    path(
        "meal_plans/<int:pk>",
        MealPlanDetailView.as_view(),
        name="meal_plans_detail",
    ),
    path(
        "meal_plans/<int:pk>/edit/",
        MealPlanUpdateView.as_view(),
        name="meal_plans_Update",
    ),
    path(
        "meal_plans/<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(null=True)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name

tags/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from meal_plans.models import MealPlan

# Create your views here.


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "mealplans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "mealplans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "mealplans/new.html"
    fields = ["name", "date", "description", "image"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "mealplans/edit.html"
    fields = ["name", "date", "select recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "mealplans/delete.html"
    success_url = reverse_lazy("my_model_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/mealplans/delete.html
{% load static %}
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            <h3>Are you sure you want to delete "{{ tag.name }}"?</h3>
            {{ form.as_p }}
            <div>
                <button class="button">Delete</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

meal_plans/templates/mealplans/detail.html
{% load static %}
{% load markdownify %}
{% extends 'base.html' %}

{% block content %}
<main class="recipe-detail">
    <div>
        <a href="{% url 'mealplans_edit' meal_plan.pk %}">Edit</a>
        <a href="{% url 'mealplans_delete' meal_plan.pk %}">Delete</a>
    </div>
    <h2>Recipes for {{ meal_plan.name }}</h2>
    {% for x in meal_plan.recipes.all %}
    <p>
        <a href="{% url 'recipe_detail' x.pk %}">{{ x.name }}</a>
    </p>
    {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/mealplans/edit.html
{% load static %}
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/mealplans/list.html
{% load static %}
{% extends 'base.html' %}


{% block pagination %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock pagination %}


{% block content %}
<main class="recipe-grid">
    {% for tag in tag_list %}
    <div class="recipe-card">
        <h2 class="recipe-card-title">
            <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
        </h2>
        {% for recipe in tag.recipes.all %}
        <p>
            <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        </p>
        {% endfor %}
    </div>
    {% empty %}
    <div>
        <h1>No tags, yet</h1>
        <p>
            Would you like to
            <a href="{% url 'tag_new' %}">create</a>
            one?
        </p>
    </div>
    {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/mealplans/new.html
{% load static %}
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}